version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: kbessetteudacity/reverseproxy
  backend_user:
    build:
      context: ../udagram-api-user
    image: kbessetteudacity/udagram-api-user
  backend_feed:
    build:
      context: ../udagram-api-feed
    image: kbessetteudacity/udagram-api-feed
  frontend:
    build:
      context: ../udagram-frontend
    image: kbessetteudacity/udagram-frontend