apiVersion: v1
kind: Service
metadata:
 labels:
   app: udagram-reverse-proxy
 name: udagram-reverse-proxy
spec:
 ports:
 - name: http
   port: 80
   targetPort: 80
 selector:
   app: udagram-reverse-proxy
 type: LoadBalancer